In [1]:
import numpy as np
import pandas as pd
import torch
import torchvision
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import math
from sklearn.preprocessing import StandardScaler

In [ ]:
df = pd.read_csv(r'wine.csv')
df.shape

In [ ]:
# separate input ouput:
x = df.iloc[:, 1:].values
y = df.iloc[:, [0]].values

In [ ]:
sc = StandardScaler()
x = sc.fit_transform(x)

In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state= 42)

### Custome dataset class

In [ ]:
class CustomeDataset(Dataset):

    def __init__(self, featurs, labels, tr):
        self.featurs = torch.tensor(featurs, dtype = torch.float32)
        self.labels = torch.tensor(labels, dtype = torch.long)

    def __len__(self):
        return len(self.featurs)

    def __getitem__(self, index):
        return self.featurs[index], self.labels[index]

In [ ]:
'''object of CustomeDataset Class'''

train_dataset = CustomeDataset(x_train, y_train)

In [ ]:
test_dataset = CustomeDataset(x_test, y_test)

---
### DataLoader

In [93]:
train_loader = DataLoader(train_dataset, batch_size= 4, shuffle= True, num_workers= 0)

test_loader = DataLoader(test_dataset, batch_size= 4)

### Training Loop

In [108]:
epochs = 1

for epoch in range(epochs):

    for batch_feature, batch_labels in train_loader:
        print(batch_feature, '\n',batch_labels)

tensor([[-1.1496e+00, -1.5830e-01, -7.1834e-01,  4.5195e-01, -1.0351e+00,
          4.8853e-01,  6.2319e-01,  6.5639e-02, -4.2208e-01, -9.9408e-01,
         -4.2754e-01,  9.4396e-01, -1.1747e+00],
        [ 1.0245e+00, -6.1611e-01,  8.5346e-01, -6.8914e-01, -4.0314e-01,
          2.4818e-01,  9.6454e-01, -1.1430e+00,  1.2249e+00,  2.3441e-01,
          1.2396e+00,  1.0711e+00,  1.6499e+00],
        [-1.9154e+00,  5.7138e-02,  1.9550e-01,  1.5166e-01, -2.6271e-01,
          9.6923e-01,  7.6375e-01, -3.3725e-01,  4.1893e-01, -7.8213e-01,
         -6.9078e-01,  1.0993e+00, -3.8817e-01],
        [ 9.3804e-01, -7.2383e-01,  1.2190e+00,  1.5183e-03,  2.2650e+00,
          1.0493e+00,  7.1355e-01,  1.1132e+00, -4.2208e-01,  1.4790e-01,
          1.2835e+00,  5.4847e-01,  1.5544e+00]]) 
 tensor([[2],
        [1],
        [2],
        [1]])
tensor([[ 1.3580, -0.1583, -0.2431, -0.4489,  0.3692,  1.0493,  1.2959, -1.1430,
          1.3826,  0.2993,  1.2835,  0.7886,  2.4301],
        [-0.1737, -0